### ISSUE TITLE
update: re(this new behaviour expected?)

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#63] opened 2015-05-14 00:07 UTC
![2015-05-14_00-43-33](https://cloud.githubusercontent.com/assets/6510026/7628093/84cb7536-f9d3-11e4-85a3-9a4293b98196.jpg)

**Comment by mgonzales71** [comment] 2015-05-14 07:55
![2015-05-14_00-53-42](https://cloud.githubusercontent.com/assets/6510026/7628123/e8736e68-f9d3-11e4-9234-7dbdc7147260.png)

**Comment by mgonzales71** [comment] 2015-05-14 08:01
![2015-05-14_00-56-42](https://cloud.githubusercontent.com/assets/6510026/7628174/c7daea22-f9d4-11e4-901d-cc0d53ff429c.png)

**Comment by marcelveldt** [comment] 2015-05-14 17:00
Hi Mario, thanks for noticing! 
Will fix it tomorrow

**Comment by mgonzales71** [comment] 2015-05-15 20:10
oops! ;)

new cosmetic issues with list, overlays, etc - no rush sir! - just FYI

![2015-05-15_13-05-16](https://cloud.githubusercontent.com/assets/6510026/7660971/9c59bc36-fb03-11e4-9f4f-35eb9117ab26.jpg)

**Comment by mgonzales71** [comment] 2015-05-15 20:17
oh - btw - I liked the updated fonts - right now you have a mixture of ubuntu and old roboto - what didn't look right to you with the new fonts?

I did notice a couple of double font name entries looking over the existing font sets - i will look at the entire list this weekend and see if I can clean up and remove the entries at the very least :)

one i noticed at first glance was this double entry:

        <font>
            <name>Reg28</name>
            <filename>Regular.ttf</filename>
            <size>28</size>
        </font>
        
        <font>
            <name>Reg28</name>
            
            <filename>Regular.ttf</filename>
            <size>32</size>
        </font>

**Comment by mgonzales71** [comment] 2015-05-15 20:21
also noticed unfocused list item (A) is not same height as focused list item (B) if that matters:

![2015-05-15_13-18-20](https://cloud.githubusercontent.com/assets/6510026/7661158/2b55936e-fb05-11e4-869c-37047ec09033.jpg)

**Comment by marcelveldt** [comment] 2015-05-15 22:56
Hi Mario,

fixed the issue with the overlays in biglist/lowlist, thanks for noticing.

As for the different line height in the normal list: that has Always been like that, it's on purpose because the focused item shows the info while the unfocused item doesn't.

The fonts are indeed different. I did that back then to create a difference between light, regular and bold. I have no problem in updating the font as long as the main regular font stays as close to what it is now. Also keep in mind that only limited fonts are considered fully opensource and can be redistributed with the skin.

So, it's not that I didn't like your update with the font but it needs to be reviewed. A lot of text just got way too big when I tested it so I did a quick revert of the font files only. It's okay to update the fonts, in fact the "light" font can be improved but it must stay as close to what it is now because the current font suits the skin and all sizes are adjusted for the used font. If the new font differs in size it's a hell of a job to get everything adjusted to that. You have to check every single screen/view in the skin if all content still fits. Both with normal font-setting and with the "large" option.

If you have some spare time and are willing to review every part of the skin to make the change be my guest ;-)

**Comment by mgonzales71** [comment] 2015-05-15 23:04
I will work more on fonts this weekend for you.  I may actually create a new font set for testing and on-going adjustments until all views can be checked out.

**Comment by marcelveldt** [comment] 2015-05-15 23:08
that would be really great!!!

**Comment by marcelveldt** [comment] 2015-05-15 23:08
btw: what do you think of my adjustments to the list views today ?

**Comment by mgonzales71** [comment] 2015-05-15 23:46
looks good - did you get any screams from the beta users on the forum?  i haven't read any posts yet today,

**Comment by marcelveldt** [comment] 2015-05-15 23:49
My attempt from yesterday did get some negative attention, it was the wrong direction. Today I worked a bit more on it and now it looks much better. Also confirmed on the forum :-)

**Comment by mgonzales71** [comment] 2015-05-15 23:53
hehe - yea I was shocked at the change in direction myself - the rounded corners mostly since I thought you wanted more square/sharp edges.  I like the updated look over yesterdays so right direction - funny how it's the little touches/changes that can be the most noticed and get the most feedback from folks :)

**Comment by marcelveldt** [comment] 2015-05-15 23:59
I left the rounded corners in... Still haven't decided yet if I leave it in or not. Untill now I think it's a little touch that makes it perfect. The skin is still square/sharp edged but just a little rounding on the corners. For now I think I like it :-)

**Comment by mgonzales71** [comment] 2015-05-16 00:00
personally I like the slight rounded edges - so no real complaints there.  makes things more organic - a good mixture of both works - just keep a balance I suppose and make sure it looks nice in the end!

at some point you may want to consider adding:

a "provide feedback" button in the skin settings
and an opt-in for anonymous skin usage statistics (on skin's first run?)

could help better understand the usage, demographics, hardware, etc

**Comment by marcelveldt** [comment] 2015-05-16 00:08
hehe, glad we agree on that :-)
I think it will stay this way. The skin looks more finished now.
Now getting that appearance settings stuff perfect.. will be a hell of a job to do but once finished it's amazing I think.

Good idea about the opt-in, something for on the "to do" list :-)

**Comment by mgonzales71** [comment] 2015-05-16 03:11
low list still has tiny cosmetic issues 

i would suggest watched overlay on right side of list items maybe?  having the watched overlays on the left in any of the lists feels strange actually but that is just me and the newness of it all still,

but i would move it to the right LOL hehe ;-)

![screenshot000](https://cloud.githubusercontent.com/assets/6510026/7664485/64b425b0-fb3e-11e4-90ff-e8304685df4c.png)

**Comment by mgonzales71** [comment] 2015-05-16 03:29
oh fun fun fun - one more in addition to above ;-)

ratings / stars music OSD

![screenshot004](https://cloud.githubusercontent.com/assets/6510026/7664526/037543e4-fb41-11e4-8ef3-a396805e103c.png)

**Comment by marcelveldt** [comment] 2015-05-20 15:42
forgot to update on this: all fixed in recent builds

**Closed by marcelveldt** 2015-05-20 15:42 UTC
